### ISSUE TITLE
stack size error limit

### ISSUE THREAD

**Issue by mamyAndrianteranagna** [GregorySchwartz/too-many-cells#30] opened 2020-07-24 14:33 UTC
Dear Gregory,

I'm trying to launch too-many-cells on my datasets when I get the following error:

**Language.R.Interpreter: Cannot increase stack size limit.Try increasing your stack size limit manually:$ ulimit -s unlimited
too-many-cells: setResourceLimit: permission denied (Operation not permitted)**

I do not have the right to change myself the stack limit size (I'm working on a remote server and the system admin does not want to change it too since it requires a reboot of all the system).

It would be helpfull for me if I can launch the tool without having to change this stack size limit.

Best regards,
Mamy Andrianteranagna

**Comment by GregorySchwartz** [comment] 2020-07-24 14:47
When does this happen?

**Comment by mamyAndrianteranagna** [comment] 2020-07-24 15:34
The OS is CentOS (server).
The docker image have been converted into singularity image (I have not the permission to launch docker) and I run the command like this:

"singularity run too-many-cells_20.2.2.0.simg make-tree ..."

(singularity run too-many-cells_20.2.2.0.simg make-tree -h works)

Thanks a lot for your help.

Best,
Mamy

**Comment by GregorySchwartz** [comment] 2020-07-24 16:30
Singularity seems to have a lot of permission issues when people are converting the docker...

Are you able to run `ulimit -s unlimited` at the command line? Can you run it in the singularity container?

**Comment by mamyAndrianteranagna** [comment] 2020-07-24 17:09
I'm not allowed to run ulimit -s unlimited because of permission restriction.
If the issue is due to the conversion, could you please create yourself a singularity image of the tool? Is this possible for you?
I think this can be helpfull for people who cannot run docker.

Best,
Mamy

**Comment by GregorySchwartz** [comment] 2020-07-24 17:24
You can't run ulimit in the container? I don't know what the issue is with singularity, but it might be more complicated than the conversion. Did you try the nix version as you are using linux?

**Comment by mamyAndrianteranagna** [comment] 2020-07-24 17:35
The problem is that I launch the job on the server (I cannot launch it locally because of memory limitation) and I can't be root on the server.

**Comment by GregorySchwartz** [comment] 2020-07-24 17:49
Nix does not require root after the initial installation (just like singularity). Did you try increasing ulimit in the container?

**Comment by GregorySchwartz** [comment] 2020-07-24 17:52
Also, what version of singularity are you using? Might be related: https://github.com/hpcng/singularity/issues/4701

**Comment by mamyAndrianteranagna** [comment] 2020-08-03 13:08
Dear Gregory,

Sorry for my late response (I was on hollyday).
As you suggested, I will ask our system manager to install nix in the server and use it instead of singularity. 
I will let you know.

Thanks a lot for your help.

Best,
Mamy

PS: For information, I was using singularity version 3.5.2 which is the only one installed in our system.

**Comment by GregorySchwartz** [comment] 2020-08-03 13:57
Thanks for the update! We'll see how it goes...

**Comment by GregorySchwartz** [comment] 2021-11-22 14:16
As I cannot reproduce, I am closing this issue. Please let me know if it persists.

**Closed by GregorySchwartz** 2021-11-22 14:16 UTC
