### ISSUE TITLE
Error in installation on Mac

### ISSUE THREAD

**Issue by ghoshal** [GregorySchwartz/too-many-cells#8] opened 2019-06-03 20:48 UTC
Hi,

I am trying to install on Mac osx and based on the tutorial completed all the steps. However, I am getting the following error.

stack install --flag gtk:have-quartz-gtk
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Already downloaded.                
Configuring GHC ...                                                              
Received ExitFailure 1 when running
Raw command: /Users/bibaswan/.stack/programs/x86_64-osx/ghc-8.4.3.temp/ghc-8.4.3/configure --prefix=/Users/bibaswan/.stack/programs/x86_64-osx/ghc-8.4.3/
Run from: /Users/bibaswan/.stack/programs/x86_64-osx/ghc-8.4.3.temp/ghc-8.4.3/

Thanks,

Bibaswan

**Comment by GregorySchwartz** [comment] 2019-06-04 15:06
Can you use the `--verbose` flag and put the output here? I wonder if `gawk` or `awk` has something to do with this, like in https://github.com/commercialhaskell/stack/issues/4426.

**Comment by ghoshal** [comment] 2019-06-12 21:03
Here is the full error.

stack install --flag gtk:have-quartz-gtk --verbose
Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1
2019-06-04 11:19:05.542601: [debug] Checking for project config at: /Users/bibaswan/Documents/programs/too-many-cells/stack.yaml
2019-06-04 11:19:05.543843: [debug] Loading project config file stack.yaml
2019-06-04 11:19:05.546561: [debug] Decoding build plan from: /Users/bibaswan/.stack/build-plan/lts-12.0.yaml
2019-06-04 11:19:05.546641: [debug] Trying to decode /Users/bibaswan/.stack/build-plan-cache/lts-12.0.cache
2019-06-04 11:19:05.552307: [debug] Success decoding /Users/bibaswan/.stack/build-plan-cache/lts-12.0.cache
2019-06-04 11:19:05.552644: [debug] Potential GHC builds: standard
2019-06-04 11:19:05.552734: [debug] Found already installed GHC builds: 
2019-06-04 11:19:05.721737: [debug] Trying to setup GHC build: standard
2019-06-04 11:19:05.722217: [info] Preparing to install GHC to an isolated location.
2019-06-04 11:19:05.722286: [info] This will not interfere with any system-level installation.
2019-06-04 11:19:05.722694: [debug] Downloading from https://github.com/commercialhaskell/ghc/releases/download/ghc-8.4.3-release/ghc-8.4.3-x86_64-apple-darwin.tar.bz2 to /Users/bibaswan/.stack/programs/x86_64-osx/ghc-8.4.3.tar.bz2 ...
2019-06-04 11:19:05.722761: [debug] Will check against sha1 hash: 4509e4c1084b8b180075141a34a893c84697feba
2019-06-04 11:19:05.722820: [debug] Will check against sha256 hash: 769456a7e4a7f22731834d415ea5687f620581cd83c590cc06fdb2ae2806c40c
2019-06-04 11:19:07.658347: [info] Already downloaded.
2019-06-04 11:19:09.216723: [debug] menv = fromList [("Apple_PubSub_Socket_Render","/private/tmp/com.apple.launchd.C8NTCcJdMR/Render"),("CLICOLOR","1"),("CONDA_DEFAULT_ENV","base"),("CONDA_EXE","/Users/bibaswan/anaconda3/bin/conda"),("CONDA_PREFIX","/Users/bibaswan/anaconda3"),("CONDA_PROMPT_MODIFIER","(base) "),("CONDA_PYTHON_EXE","/Users/bibaswan/anaconda3/bin/python"),("CONDA_SHLVL","1"),("DISPLAY","/private/tmp/com.apple.launchd.shAuxCVagm/org.macosforge.xquartz:0"),("HOME","/Users/bibaswan"),("LANG","en_CA.UTF-8"),("LOGNAME","bibaswan"),("LSCOLORS","GxFxBxDxdxeghdabagacad"),("OLDPWD","/Users/bibaswan"),("PATH","/opt/local/bin:/opt/local/sbin:/Users/bibaswan/anaconda3/bin:/Users/bibaswan/anaconda3/condabin:/Users/bibaswan/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"),("PS1","(base) \\[\\033[36m\\]\\u\\[\\033[m\\]@\\[\\033[32m\\]\\h:\\[\\033[33;1m\\]\\w\\[\\033[m\\]$ "),("PWD","/Users/bibaswan/Documents/programs/too-many-cells"),("SECURITYSESSIONID","186aa"),("SHELL","/bin/bash"),("SHLVL","1"),("SSH_AUTH_SOCK","/private/tmp/com.apple.launchd.mL7ZInQXZW/Listeners"),("TERM","xterm-256color"),("TERM_PROGRAM","Apple_Terminal"),("TERM_PROGRAM_VERSION","421.2"),("TERM_SESSION_ID","A9E698B4-BE3F-4AFD-87D7-1E786DC45F65"),("TMPDIR","/var/folders/lv/26lkh7m902n85b7k_m_0gz_80000gn/T/"),("USER","bibaswan"),("XPC_FLAGS","0x0"),("XPC_SERVICE_NAME","0"),("_","/usr/local/bin/stack"),("_CE_CONDA",""),("_CE_M",""),("__CF_USER_TEXT_ENCODING","0x1F5:0x0:0x52")]
2019-06-04 11:19:09.219848: [debug] ziptool: bzip2
2019-06-04 11:19:09.219906: [debug] make: make
2019-06-04 11:19:09.219956: [debug] tar: tar
2019-06-04 11:19:09.220028: [debug] Unpacking /Users/bibaswan/.stack/programs/x86_64-osx/ghc-8.4.3.tar.bz2
2019-06-04 11:19:09.220396: [debug] Run process within /Users/bibaswan/.stack/programs/x86_64-osx/ghc-8.4.3.temp/: /usr/bin/tar jxf /Users/bibaswan/.stack/programs/x86_64-osx/ghc-8.4.3.tar.bz2
2019-06-04 11:19:56.096232: [debug] Process finished in 46878ms: /usr/bin/tar jxf /Users/bibaswan/.stack/programs/x86_64-osx/ghc-8.4.3.tar.bz2
2019-06-04 11:19:56.096597: [debug] Run process within /Users/bibaswan/.stack/programs/x86_64-osx/ghc-8.4.3.temp/ghc-8.4.3/: /Users/bibaswan/.stack/programs/x86_64-osx/ghc-8.4.3.temp/ghc-8.4.3/configure --prefix=/Users/bibaswan/.stack/programs/x86_64-osx/ghc-8.4.3/
2019-06-04 11:19:57.526391: [debug] checking build system type... x86_64-apple-darwin18.6.0
2019-06-04 11:19:57.526790: [debug] checking host system type... x86_64-apple-darwin18.6.0
2019-06-04 11:19:57.527178: [debug] checking target system type... x86_64-apple-darwin18.6.0
2019-06-04 11:19:57.527884: [debug] Build platform inferred as: x86_64-apple-darwin
2019-06-04 11:19:57.542097: [debug] Host platform inferred as: x86_64-apple-darwin
2019-06-04 11:19:57.562031: [debug] Target platform inferred as: x86_64-apple-darwin
2019-06-04 11:19:57.634640: [debug] GHC build  : x86_64-apple-darwin
2019-06-04 11:19:57.634783: [debug] GHC host   : x86_64-apple-darwin
2019-06-04 11:19:57.634861: [debug] GHC target : x86_64-apple-darwin
2019-06-04 11:19:57.634920: [debug] LLVM target: x86_64-apple-darwin
2019-06-04 11:19:57.641366: [debug] checking for path to top of build tree... /Users/bibaswan/.stack/programs/x86_64-osx/ghc-8.4.3.temp/ghc-8.4.3
2019-06-04 11:19:57.643070: [debug] checking for perl... /Users/bibaswan/anaconda3/bin/perl
2019-06-04 11:19:57.672030: [debug] checking for a BSD-compatible install... /usr/bin/install -c
2019-06-04 11:19:57.673138: [debug] checking for gfind... no
2019-06-04 11:19:57.674068: [debug] checking for find... /usr/bin/find
2019-06-04 11:19:57.685424: [debug] checking whether ln -s works... yes
2019-06-04 11:19:57.686499: [debug] checking for gsed... sed
2019-06-04 11:19:58.726128: [debug] checking XCode version... 10.2.1
2019-06-04 11:19:58.735279: [debug] configure: XCode version component 1: 10
2019-06-04 11:19:58.735407: [debug] configure: XCode version component 2: 2
2019-06-04 11:19:58.736418: [debug] checking for gcc... gcc
2019-06-04 11:19:59.068437: [debug] checking whether the C compiler works... yes
2019-06-04 11:19:59.068578: [debug] checking for C compiler default output file name... a.out
2019-06-04 11:19:59.153121: [debug] checking for suffix of executables... 
2019-06-04 11:19:59.313352: [debug] checking whether we are cross compiling... no
2019-06-04 11:19:59.383301: [debug] checking for suffix of object files... o
2019-06-04 11:19:59.447500: [debug] checking whether we are using the GNU C compiler... yes
2019-06-04 11:19:59.513558: [debug] checking whether gcc accepts -g... yes
2019-06-04 11:19:59.639601: [debug] checking for gcc option to accept ISO C89... none needed
2019-06-04 11:19:59.720229: [debug] checking how to run the C preprocessor... gcc -E
2019-06-04 11:20:00.430518: [debug] checking for gcc option to accept ISO C99... unsupported
2019-06-04 11:20:00.430733: [debug] configure: error: C99-compatible compiler needed
Configuring GHC ...
Received ExitFailure 1 when running
Raw command: /Users/bibaswan/.stack/programs/x86_64-osx/ghc-8.4.3.temp/ghc-8.4.3/configure --prefix=/Users/bibaswan/.stack/programs/x86_64-osx/ghc-8.4.3/
Run from: /Users/bibaswan/.stack/programs/x86_64-osx/ghc-8.4.3.temp/ghc-8.4.3/

**Comment by GregorySchwartz** [comment] 2019-06-13 13:55
Thanks for the info. This looks like it seems to be an issue with your C compilier: https://github.com/commercialhaskell/stack/issues/4186. It seems like https://github.com/SOHU-Co/kafka-node/issues/881#issuecomment-396197724 fixes it, but I would be cautious. Following that thread, https://github.com/SOHU-Co/kafka-node/issues/881#issuecomment-443995175 seems to be a solution, but I can't test any of these issues. This error seems to be hitting a lot of MacOS C programs, based on what I see from these issues.

**Comment by GregorySchwartz** [comment] 2019-11-01 20:20
Any luck? The `too-many-cells` R wrapper (https://cran.r-project.org/web/packages/TooManyCellsR/index.html) has been updated to allow for docker, if that's any help.

**Comment by maxlobel1** [comment] 2020-01-14 13:08
I'm running into this same issue while trying to install the blosum table generator. I can't seem to get this error to solve using this method: https://github.com/SOHU-Co/kafka-node/issues/881#issuecomment-396197724. Attempting to use this method: https://github.com/SOHU-Co/kafka-node/issues/881#issuecomment-443995175 resulted in an error telling me that no such keg exists. Any suggestions?

**Comment by GregorySchwartz** [comment] 2020-01-15 15:29
@maxlobel1 Also found that `xcode-select --install` may fix missing xcrun errors. Seems to be related to upgrading macOS. Closing for now until more information is given as I cannot reproduce an issue.

**Closed by GregorySchwartz** 2020-01-15 15:29 UTC
